import jwt from 'jsonwebtoken';
import User from '../models/userModel.js';

const JWT_SECRET = process.env.JWT_SECRET || 'your-secret-key-change-in-production';
const ADMIN_ACCESS_CODE = process.env.ADMIN_ACCESS_CODE || 'GPT2024SLOT';

class AuthController {
    async register(req, res) {
        try {
            const { username, email, password } = req.body;

            // Check if user exists
            const existingUser = await User.findOne({ $or: [{ email }, { username }] });
            if (existingUser) {
                return res.status(400).json({ 
                    message: 'User with this email or username already exists' 
                });
            }

            // Create new user (password will be hashed & accessCode auto-generated by pre-save hook)
            const user = new User({ username, email, password });
            await user.save();

            // Generate JWT token
            const token = jwt.sign(
                { userId: user._id, username: user.username },
                JWT_SECRET,
                { expiresIn: '7d' }
            );

            res.status(201).json({
                message: 'User registered successfully',
                token,
                user: {
                    id: user._id,
                    username: user.username,
                    email: user.email,
                    isCodeVerified: false
                },
                notice: '⚠️ Vui lòng liên hệ admin để nhận mã truy cập 16 ký tự của bạn. Admin sẽ xem trong MongoDB Compass.'
            });
        } catch (error) {
            console.error('Registration error:', error);
            res.status(500).json({ message: 'Error registering user', error: error.message });
        }
    }

    async login(req, res) {
        try {
            const { username, password } = req.body;

            // Find user by username OR email
            const user = await User.findOne({ 
                $or: [{ username }, { email: username }] 
            });
            if (!user) {
                return res.status(401).json({ message: 'Invalid credentials' });
            }

            // Check if user is banned
            if (user.isBanned) {
                return res.status(403).json({ 
                    message: '🚫 Tài khoản đã bị khóa vĩnh viễn',
                    isBanned: true,
                    bannedAt: user.bannedAt,
                    banReason: user.banReason || 'Nhập sai mã truy cập 3 lần liên tiếp'
                });
            }

            // Check password
            const isPasswordValid = await user.comparePassword(password);
            if (!isPasswordValid) {
                return res.status(401).json({ message: 'Invalid credentials' });
            }

            // Generate JWT token
            const token = jwt.sign(
                { userId: user._id, username: user.username },
                JWT_SECRET,
                { expiresIn: '7d' }
            );

            res.status(200).json({
                message: 'Login successful',
                token,
                user: {
                    id: user._id,
                    username: user.username,
                    email: user.email,
                    isCodeVerified: user.isCodeVerified,
                    isBanned: user.isBanned,
                    failedAttempts: user.codeAttempts?.failed || 0,
                    remainingAttempts: Math.max(0, 3 - (user.codeAttempts?.failed || 0))
                }
            });
        } catch (error) {
            console.error('Login error:', error);
            res.status(500).json({ message: 'Error logging in', error: error.message });
        }
    }

    async getProfile(req, res) {
        try {
            const user = await User.findById(req.userId).select('-password');
            if (!user) {
                return res.status(404).json({ message: 'User not found' });
            }
            
            // Include ban status and attempt info
            const attemptCheck = user.canAttemptCode();
            
            res.status(200).json({ 
                user: {
                    ...user.toObject(),
                    canAttemptCode: attemptCheck.allowed,
                    remainingAttempts: attemptCheck.allowed ? attemptCheck.remainingAttempts : 0
                }
            });
        } catch (error) {
            res.status(500).json({ message: 'Error fetching profile', error: error.message });
        }
    }

    // DEPRECATED: Old access code verification (replaced by accessCodeController)
    // Kept for backward compatibility - redirects to new system
    async verifyAccessCode(req, res) {
        return res.status(410).json({
            message: 'This endpoint is deprecated. Please use POST /api/access-codes/verify',
            newEndpoint: '/api/access-codes/verify',
            deprecated: true
        });
    }
    // DEPRECATED: Old access code verification (replaced by accessCodeController)
    // Kept for backward compatibility - redirects to new system
    async verifyAccessCode(req, res) {
        return res.status(410).json({
            message: 'This endpoint is deprecated. Please use POST /api/access-codes/verify',
            newEndpoint: '/api/access-codes/verify',
            deprecated: true
        });
    }
}

export default AuthController;
